### ISSUE TITLE
Import Coordinates into the Location Generator

### ISSUE THREAD

**Issue by KensonN** [bunzosteele/PokeWatch#66]
Is there any way we can import our old coordinates into the generator so that we can edit them due to the radius change? Also, can you add a search bar to the map in the location generator?

**Comment by RedSparr0w** [comment]
Click import config to import your current coordinates and add to it
edit: using the new ConfigGenerator.html https://github.com/bunzosteele/PokeWatch/blob/master/ConfigGenerator.html

Sent from my iPhone

On 2/08/2016, at 6:22 PM, KensonN <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there any way we can import our old coordinates into the generator so that we can edit them due to the radius change? Also, can you add a search bar to the map in the location generator?

##

**Comment by KensonN** [comment]
Alright. Thanks!
