### ISSUE TITLE
Twitter Authentication Errors

### ISSUE THREAD

**Issue by KensonN** [bunzosteele/PokeWatch#74]
I've been getting authentication errors for all 12 of my bots. It's been working fine for the past few days, but when I restarted the program, I now get errors. Is it because I'm starting the bots too quickly?

**Comment by bunzosteele** [comment]
Seeing this as well, (running 11 bots), I think if all bots go down at once, and therefore try to reconnect all at once, twitter starts rejecting the authentication requests because there are so many. The solution I've found is to wait a few minutes then spin them back up one at a time, hopefully this won't be an issue with the new launcher

**Comment by KensonN** [comment]
yep. that did it

**Comment by bunzosteele** [comment]
New error handling should react to Twitter Rate limiting and adjust reboot speed accordingly
https://www.reddit.com/r/pokewatch/comments/4xioal/pokewatch_v4/
