### ISSUE TITLE
Crash after tweet is composing

### ISSUE THREAD

**Issue by KensonN** [bunzosteele/PokeWatch#8]
The program crashes, saying "Demo has stopped working". 

The log: http://pastebin.com/bT2DaZYq

**Comment by bunzosteele** [comment]
Until this is fixed, you can follow this step from the OPTIONAL section of the readme to allow the bot to reboot itself and not need supervision:
b. PokewatchLauncher.exe will restart pokewatch any time it dies in the middle of running (usually due to server outages). By default on most machines, OS will prompt you to acknowlege the crash before PokewatchLauncher, can reset the application, to disable this and allow the app to run indefinitely without supervision, follow this guide: https://www.raymond.cc/blog/disable-program-has-stopped-working-error-dialog-in-windows-server-2008/

**Comment by KensonN** [comment]
Alright. Disabled the error message. Thanks for the quick response!
